varialvel = '1'
variavel2 = 2

puts varialvel.to_i + 2




# TO_I - CONVERTE A VARIÁVEL INTEIRO.
# TO_F - CONVERTE A VARIÁVEL FLOAT.
# TO_S - CONVERTE A VARIÁVEL PARA STRING.
# TO_A – CONVERTE A VARIÁVEL PARA ARRAY.
# TO_SYM - CONVERTE A VARIÁVEL PARA SÍMBOLO.